### ISSUE TITLE
Expose RequestHandler and T

### ISSUE THREAD

**Issue by yurishkuro** [crossdock/crossdock-go#5]
I've migrated Jaeger client to use this repo for client code, but had to leave a couple pieces untouched because the similar functionality is private in crossdock.
1. I cannot use `crossdock.Start()` directly because I need a way to configure some private members of the client class. Any objection to exposing the `requestHandler` as public?
2. Any objection to exposing a constructor for `entryT`? For example, I cannot unit test [this function](https://github.com/uber/jaeger-client-go/blob/master/crossdock/client/trace.go#L91) without it.

**Comment by HelloGrayson** [comment]
1. I'm not opposed to it, @abhinav what do you think? @yurishkuro why do you need to customize the client class? Couldn't you put that stuff somewhere else?
2. That seems like a good idea.

**Comment by yurishkuro** [comment]
>  @yurishkuro why do you need to customize the client class? Couldn't you put that stuff somewhere else?

When used in unit tests, the downstream servers that the client calls are running on random ports, so we need to tell the client where those ports are. Thus a client is always started as an instance of the Client struct, not via static methods. Note that I don't actually need to change how client works in crossdock, I just want the `requestHandler` exposed so that I can attach it to our client, to reuse its dispatching functionality.

**Comment by HelloGrayson** [comment]
@yurishkuro is this in OSS? Send us a link to where you're doing that.

**Comment by yurishkuro** [comment]
- https://github.com/uber/jaeger-client-go/blob/master/crossdock/client/client.go#L108
- https://github.com/uber/jaeger-client-go/blob/master/crossdock/client/client_test.go#L35

**Comment by abhinav** [comment]
@yurishkuro Regarding entryT, can't you use [`Run`](https://sourcegraph.com/github.com/crossdock/crossdock-go@e53a1feb15cb012ae9b6691f1acdaa62b480cf92/-/def/GoPackage/github.com/crossdock/crossdock-go/-/Run)? Without `Run`, there's no guarantee that the `FailNow`-based functions will work correctly, because they rely on the call executing in its own goroutine to support `FailNow`.

To test the example you mentioned, you would use `Run`, and then assert conditions about the returned collection of `Entry` objects.

**Comment by abhinav** [comment]
Also, you mentioned that you just want to reuse the `requestHandler` dispatching logic. Instead of exporting the type, can you export a function `func Handler(Behaviors) http.Handler`?

**Comment by yurishkuro** [comment]
@abhinav yes, I might be able to use `Run`. Not sure what you mean about `func Handler(Behaviors) http.Handler`. In my client the `behaviorRequestHandler` and `dispatch` functions are boilerplate, I could've easily used crossdock `requestHandler`, however it is exposed.

**Comment by abhinav** [comment]
Agreed, I mean instead of exposing `requestHandler` the type, we can get crossdock-go to expose,

``` go
package crossdock

func Handler(b Behaviors) http.Handler {
  return requestHandler{Behaviors: b}
}
```

Then in your code, you can replace `behaviorRequestHandler` and `dispatch` with,

``` go
http.Handle("/", crossdock.Handler(behaviors))
```

Where behaviors is a `map[string]func(T)` (as defined [here](https://sourcegraph.com/github.com/crossdock/crossdock-go@e53a1feb15cb012ae9b6691f1acdaa62b480cf92/-/def/GoPackage/github.com/crossdock/crossdock-go/-/Behaviors)).

**Comment by HelloGrayson** [comment]
@abhinav that looks right to me

**Comment by HelloGrayson** [comment]
@yurishkuro do you want to take a stab at @abhinav's suggestion?

**Comment by yurishkuro** [comment]
ok
